version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: food-delivery-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: food_delivery
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: food-delivery-redis
    restart: unless-stopped
    ports:
      - "16379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: food-delivery-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "12181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: food-delivery-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: food-delivery-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data: