global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "order-service"
    static_configs:
      - targets: ["host.docker.internal:9091"]
  - job_name: "payment-service"
    static_configs:
      - targets: ["host.docker.internal:9092"]
  - job_name: "inventory-service"
    static_configs:
      - targets: ["host.docker.internal:9093"]